teste.cpp:
	g++ -c teste.cpp `libpng-config --cflags` -o teste.o -std=c++2a -O2 -Wall -Wextra -pedantic -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -Wno-unused-result -Wno-sign-conversion 
	g++ -o teste teste.o `libpng-config --ldflags`